# Generated by Django 2.0.4 on 2018-04-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': 'courseOrg', 'verbose_name_plural': 'courseOrg'},
        ),
    ]
