# Generated by Django 2.0.4 on 2018-04-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resource'},
        ),
    ]
