# Generated by Django 2.0.4 on 2018-04-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180409_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': ('UserProfile',), 'verbose_name_plural': ('UserProfile',)},
        ),
    ]
