# Generated by Django 2.0.4 on 2018-04-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180410_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': 'emailVerifyCode', 'verbose_name_plural': 'emailVerifyCode'},
        ),
    ]
